// <auto-generated />
using System;
using CMDAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMDAPI.Migrations
{
    [DbContext(typeof(CommandContext))]
    [Migration("20190808050409_Added Foregin key from FoodeQty to Invoice table")]
    partial class AddedForeginkeyfromFoodeQtytoInvoicetable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMDAPI.Models.FoodItem", b =>
                {
                    b.Property<int>("foId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("foName");

                    b.Property<double>("foRate");

                    b.HasKey("foId");

                    b.ToTable("FoodItem");
                });

            modelBuilder.Entity("CMDAPI.Models.FoodQty", b =>
                {
                    b.Property<int>("fqId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("foId");

                    b.Property<string>("foodName");

                    b.Property<int>("foodQty");

                    b.Property<double>("foodTotal");

                    b.HasKey("fqId");

                    b.HasIndex("foId");

                    b.ToTable("FoodQty");
                });

            modelBuilder.Entity("CMDAPI.Models.HTable", b =>
                {
                    b.Property<int>("tabId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tabLocations");

                    b.Property<string>("tabName");

                    b.HasKey("tabId");

                    b.ToTable("HTable");
                });

            modelBuilder.Entity("CMDAPI.Models.Invoice", b =>
                {
                    b.Property<int>("invId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("fqId");

                    b.Property<string>("gst");

                    b.Property<double>("invSubTotal");

                    b.Property<double>("invTotal");

                    b.Property<int>("tabId");

                    b.HasKey("invId");

                    b.HasIndex("fqId");

                    b.HasIndex("tabId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("CMDAPI.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at");

                    b.Property<string>("email");

                    b.Property<string>("name");

                    b.Property<string>("password");

                    b.Property<string>("username");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CMDAPI.Models.FoodQty", b =>
                {
                    b.HasOne("CMDAPI.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("foId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CMDAPI.Models.Invoice", b =>
                {
                    b.HasOne("CMDAPI.Models.FoodQty", "FoodQty")
                        .WithMany()
                        .HasForeignKey("fqId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CMDAPI.Models.HTable", "HTable")
                        .WithMany()
                        .HasForeignKey("tabId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
